microhr/models.py
from django.conf import settings
from django.db import models

from accounts.models import User

# Create your models here.


class Work(models.Model):
    title = models.CharField('タイトル', max_length=128)
    company = models.ForeignKey(settings.AUTH_USER_MODEL,
                                verbose_name='企業',
                                on_delete=models.CASCADE)
    salary_max = models.IntegerField()
    salary_min = models.IntegerField()
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Application(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    work = models.ForeignKey(Work,
                                on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_passed = models.BooleanField(null=True, help_text='合格ならTrue')

class Favorite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    work = models.ForeignKey(Work,
                                on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class CompanyFavorite(models.Model):
    company = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE
                                )
    worker = models.ForeignKey(User,
                                on_delete=models.CASCADE,
                                related_name="favorite_worker"
                                )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)                            

microhr/templates/work/applicant_detail.html
{% extends 'base.html' %}
{% block main %}
<h1 class="mb-5">{{ application.user.name }}の履歴書</h1>
<h5>経歴</h5>
<p>{{ application.user.workerprofile.resume }}</p>
<h5>自己ＰＲ</h5>
<p>{{ application.user.workerprofile.self_pr }}</p>
    {% if application.is_passed is None %}
        <p>現在のステータス：<strong>選考中</strong></p>
    {% elif application.is_passed %}
        <p>現在のステータス：<strong>合格</strong></p>
    {% else %}
        <p>現在のステータス：<strong>不合格</strong></p>
    {% endif %}

<form action="{% url 'application_detail' application.id %}" method="post">
{% csrf_token %}
    <input type="radio" id="passed" name="judge" value="True">
    <label for="passed">合格</label>
    
    <input type="radio" id="fail" name="judge" value="False">
    <label for="fail">不合格</label>

    <input type="radio" id="in-progress" name="judge" value="None">
    <label for="in-progress">選考中</label>
    
    <button type="submit" class="btn btn-primary">変更する</button>
</form>
<form action="{% url 'favorite_worker' application.user.id %}" method="post">
{% csrf_token %}
    <button type="submit" class="btn btn-primary">気になる</button>
</form>
{% endblock %}

microhr/templates/work/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load humanize %}

{% block main %}
<h1>{{ work.title }}</h1>
<table class="table">
    <tr>
        <td>会社名</td>
        <td>{{ work.company.name }}</td>
    </tr>
    <tr>
        <td>給与</td>
        <td>{{ work.salary_min | intcomma }}万円 ~ {{ work.salary_max | intcomma }}万円</td>
    </tr>
    <tr>
        <td></td>
        <td>
            {{ work.text | linebreaksbr}}
        </td>
    </tr>
    <tr>
        <td>求人登録日</td>
        <td>{{ work.created_at | date:"Y年n月j日 H:i:s"}}</td>
    </tr>
    <tr>
        <td>最終更新日</td>
        <td>{{work.updated_at | date:"Y年n月j日 H:i:s"}}</td>
    </tr>
</table>

<div>
    {% if user.is_authenticated and user.is_company and user == work.company %}
    <a class="btn btn-primary" href="{% url 'work_edit' work.id %}">編集する</a>
    <form method="post" action="{% url 'work_delete' work.id %}" style="display:inline;">
        {% csrf_token %}
        <button type="submit" name="delete_button" class="btn btn-primary" id="btn_del">削除する</button>
    </form>
    {% elif not user.is_company %}
    <form method="post" action="{%url 'work_apply' work.id %}" style="display:inline;">
    {% csrf_token %}
        <button type="submit" name="apply_button" class="btn btn-primary" id="btn_apply">応募する</a>
    </form>        
    <form method="post" action="" style="display: inline;">
    {% csrf_token %}
        <button type="submit" name="fav_button" class="btn btn-secondary ms-2">気になる</button>
    </form>
    {% endif %}
    

<script>
    $(function () {

        $("#btn_apply").click(function(){
            if(!confirm("応募しますか？")){
                //cancelなら応募しない
                return false;                
            }else{
                alert('応募完了後、応募一覧に移動します')         
            }
        });
  
        $("#btn_del").click(function(){
            if(!confirm("削除しますか？")){
                //cancelなら削除しない
                return false;
            }else{
                alert('削除完了後、HOMEに移動します')
            }
        });
    });
</script>
{% endblock %}

microhr/templates/work/favorite.html
{% extends 'base.html' %}
{% block main %}
<h1 class="mb-5">気になる一覧</h1>
{% for favorite in favorites %}
    <p>企業名：<strong>{{ favorite.work.company }}</strong></p>
    <a href="{% url 'work_detail' favorite.work.id %}">{{ favorite.work }}</a>
    <form method="post" action="{% url 'favorite_delete' favorite.id %}" class="mt-3">
    {% csrf_token %}
        <button type="submit" class="btn btn-primary">気になるを削除する</button>
    </form>
{% endfor %}
{% endblock %}

microhr/templates/work/favorite_worker.html
{% extends 'base.html' %}
{% block main %}
<h1>気になる一覧</h1>
{% for favoriteworker in favoriteworkers %}
    <p>ユーザー：<strong>{{ favoriteworker.worker }}</strong></p>
    <p>経歴:{{ favoriteworker.worker.workerprofile.resume }}</p>
    <p>PR文:{{ favoriteworker.worker.workerprofile.self_pr}}</p>
    <form method="post" action="{% url 'favoriteworker_delete' favoriteworker.id %}" class="mt-3">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">気になるを削除する</button>
    </form>
{% endfor %}
{% endblock %}

microhr/templates/work/items.html
{% extends 'base.html' %}
{% block main %}
<h1>応募一覧</h1>
{% if applications %}
<table class="table">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>会社名</th>
            <th>給料</th>
            <th>合否</th>
        </tr>
    </thead>
    <tbody>
    {% for application in applications %}
        <tr>
            <td>{{ application.work.title }}</td>
            <td>{{ application.work.company }}</td>
            <td>{{ application.work.salary_min }}万円～{{ application.work.salary_max }}万円</td>
            <td>
                {% if application.is_passed == null %}
                結果をお待ちください。
                {% elif application.is_passed == True %}
                合格
                {% else %}
                落選
                {% endif %}
            </td>
        </tr>
    {% endfor %} 
    </tbody>
</table>
{% else %}
応募企業はありません。
{% endif %}
{% endblock %}

microhr/templates/work/selection.html
{% extends 'base.html' %}
{% block main %}
<h1 class="mb-5">選考</h1>
{% if works %}    
    
<div class="accordion accordion-flush" id="accordion">
    {% for work in works %}
    <div class="accordion-item">
      <h2 class="accordion-header" id="heading{{ forloop.counter }}">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
          <h5>{{ work.title }}</h5>
        </button>
      </h2>
      <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse" aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#accordion">
        <div class="accordion-body">
          <h6>応募者</h6>
            {% with applications=work.application_set.all %}
            <ul class="listgroup list-group-flush">
                {% for a in applications %}                    
                  <li class="list-group-item">
                    <a href="{% url 'application_detail' a.id %}" class="me-5">{{ a.user }}</a>
                {% if a.is_passed is None %}
                選考中
                {% elif a.is_passed == True %}
                合格
                {% else %}
                落選
                {% endif %}
                  </li>                                            
                {% endfor %}
              </ul> 
            {% endwith %}
          <h6>気になる登録者</h6>
          {% with favorites=work.favorite_set.all %}
              {% for favorite in favorites %}
              <a href="{% url 'application_detail' favorite.user.id %}" class="me-5">{{ favorite.user }}</a>
              {% endfor %}
          {% endwith %}
        </div>
      </div>
    </div>
    {% endfor %}
</div>

{% else %}
応募者はいません。
{% endif %}
{% endblock %}